version: '2'

services:
  # Easy way to reference our source code.
  src:
    image: busybox
    volumes:
      - ./api:/srv/api
      - ./web:/srv/web

  # Main entry point to the application
  router:
    build: router
    links:
      - api
      - web
    ports:
      - 80:80

  api: &ruby_base
    build: ./api
    command: script/servers/start
    volumes_from:
      - src

  postgres:
    build: databases/postgres
    volumes:
      - .pgdata:/var/lib/postgresql/

  web:
    build: web
    command: gulp serve-dev
    volumes_from:
      - src
    ports:
      - 3000:3000
